lib/rom/command_registry.rb, spec/integration/commands/try_spec.rb
This PR addresses #83
/cc @solnic
=> Pass command to block in CommandRegistry#try

lib/rom/support/options.rb
Move validation code into class.
After this commit including `Options` exposes less class methods:
* `option` and
* `option_definitions`
Feedback is welcome!
=> Refactor Options module

.travis.yml
See https://github.com/jruby/jruby/wiki/Improving-startup-time#use-the---dev-flag
*Waiting for Travis*
=> Improve JRuby's startup time on Travis

Guardfile
See individual commit messages.
I can squash commits if desired.
=> Cleanup Guardfile

lib/rom/command_registry.rb, lib/rom/env.rb, lib/rom/relation_builder.rb, lib/rom/setup.rb, lib/rom/support/registry.rb, spec/integration/commands/try_spec.rb
=> Refactor several `method_missing`s to use `fetch` along with `super`

lib/rom/mapper.rb, lib/rom/reader.rb, spec/unit/rom/reader_spec.rb
=> Add one and one! to Reader

lib/rom/relation/lazy.rb, spec/unit/rom/relation/lazy_spec.rb
=> Allow default arguments in relations

lib/rom.rb, lib/rom/command.rb, lib/rom/constants.rb, lib/rom/global.rb, lib/rom/mapper/dsl.rb, lib/rom/plugin.rb, lib/rom/plugin_registry.rb, lib/rom/relation/class_interface.rb, lib/rom/setup_dsl/plugin_dsl.rb, lib/rom/setup_dsl/setup.rb, spec/unit/rom/plugin_spec.rb
wip for peeking over my shoulder; I'll probably rebase this heavily before it's actually ready to merge.
closes #192
=> Plugin registry

Gemfile, lib/rom/header.rb, lib/rom/header/attribute.rb, lib/rom/mapper/attribute_dsl.rb, lib/rom/processor/transproc.rb, lib/rom/relation/composite.rb, spec/integration/mappers/combine_spec.rb
=> Add `combine` interface to mapping DSL

.rubocop.yml, benchmarks/basic_bench.rb, benchmarks/setup.rb, lib/rom.rb, lib/rom/lint/enumerable_dataset.rb, lib/rom/mapper/attribute_dsl.rb, lib/rom/memory/commands.rb, lib/rom/plugin_registry.rb, lib/rom/processor/transproc.rb, lib/rom/setup/finalize.rb, spec/integration/commands/create_spec.rb, spec/integration/mappers/combine_spec.rb, spec/integration/mappers/unwrap_spec.rb, spec/integration/multi_repo_spec.rb, spec/integration/setup_spec.rb, spec/shared/enumerable_dataset.rb, spec/spec_helper.rb, spec/unit/rom/commands_spec.rb, spec/unit/rom/mapper/dsl_spec.rb, spec/unit/rom/memory/storage_spec.rb, spec/unit/rom/plugin_spec.rb, spec/unit/rom/relation/composite_spec.rb, spec/unit/rom/relation/lazy/combine_spec.rb, spec/unit/rom/relation/lazy_spec.rb, spec/unit/rom/relation/loaded_spec.rb, spec/unit/rom/setup_spec.rb, spec/unit/rom/support/array_dataset_spec.rb, spec/unit/rom/support/class_builder_spec.rb
=> Cleanup most rubocop offenses

CHANGELOG.md, lib/rom/memory/dataset.rb, spec/unit/rom/memory/relation_spec.rb
Allowed ordering by multiple keys when some values are empty
This is #226 selected to the separate branch
=> Fixed #order for memory relation

.rspec, lib/rom/commands/abstract.rb, lib/rom/commands/composite.rb, lib/rom/commands/graph.rb, lib/rom/memory/commands.rb, spec/unit/rom/commands/graph_spec.rb
This adds `combine` interface to Commands that allows you to build a command which will return a graph that can be mapped using combine mapping just like in case of relations.
closes #214
=> [WIP] Command Graph

lib/rom/header.rb, lib/rom/header/attribute.rb, lib/rom/mapper/attribute_dsl.rb, lib/rom/processor/transproc.rb, spec/integration/mappers/unfold_spec.rb, spec/integration/mappers/ungroup_spec.rb
Added `ungroup` and `unfold` as inversions for `group` and `fold`
=> Nested operations

lib/rom/commands/result.rb, spec/unit/rom/commands/result_spec.rb
Hello @solnic, I realized #266 issue, please review my code :pray:
=> Add success? and failure? to ROM::Commands::Result

lib/rom/schema.rb, spec/integration/setup_spec.rb
This fixes https://github.com/rom-rb/rom-sql/issues/78
=> Allow a relation with a schema be in multiple containers

lib/rom.rb, lib/rom/container.rb, lib/rom/create_container.rb
=> Remove usage of ROM::Support::Publisher

Gemfile, lib/rom.rb, lib/rom/array_dataset.rb, lib/rom/association_set.rb, lib/rom/auto_curry.rb, lib/rom/commands/graph.rb, lib/rom/data_proxy.rb, lib/rom/enumerable_dataset.rb, lib/rom/mapper_registry.rb, lib/rom/memory/dataset.rb, lib/rom/plugin_registry.rb, lib/rom/registry.rb, lib/rom/relation/class_interface.rb, lib/rom/setup/finalize.rb, lib/rom/setup/finalize/finalize_commands.rb, lib/rom/setup/finalize/finalize_mappers.rb, spec/shared/enumerable_dataset.rb, spec/unit/rom/array_dataset_spec.rb, spec/unit/rom/auto_curry_spec.rb, spec/unit/rom/enumerable_dataset_spec.rb, spec/unit/rom/registry_spec.rb
Still on the list
* ClassMacros
* ROM::Options (I guess we can use dry-initializer, I'll give it a try)
=> Move modules from rom-support to rom

.travis.yml, CHANGELOG.md, Gemfile, lib/rom/array_dataset.rb, lib/rom/command.rb, lib/rom/command_registry.rb, lib/rom/commands/graph.rb, lib/rom/data_proxy.rb, lib/rom/enumerable_dataset.rb, lib/rom/initializer.rb, lib/rom/memory/dataset.rb, lib/rom/plugins/relation/registry_reader.rb, lib/rom/relation.rb, lib/rom/relation/class_interface.rb, lib/rom/relation/curried.rb, lib/rom/setup/auto_registration.rb, lib/rom/setup/auto_registration_strategies/base.rb, lib/rom/setup/auto_registration_strategies/custom_namespace.rb, lib/rom/setup/auto_registration_strategies/no_namespace.rb, lib/rom/setup/auto_registration_strategies/with_namespace.rb, lib/rom/types.rb, rom.gemspec, spec/integration/commands/create_spec.rb, spec/integration/commands/update_spec.rb, spec/unit/rom/relation_spec.rb
@solnic here we're go :)
I've got an issue with dry-initializer under MRI 2.4, will see what Travis says
=> Replace ROM::Options with dry-initializer

Gemfile, lib/rom/command.rb, lib/rom/command_registry.rb, lib/rom/commands/graph.rb, lib/rom/data_proxy.rb, lib/rom/initializer.rb, lib/rom/plugins/relation/instrumentation.rb, lib/rom/plugins/relation/registry_reader.rb, lib/rom/relation.rb, lib/rom/relation/class_interface.rb, lib/rom/relation/curried.rb, lib/rom/setup/auto_registration.rb, lib/rom/setup/auto_registration_strategies/base.rb, lib/rom/setup/auto_registration_strategies/custom_namespace.rb, lib/rom/setup/auto_registration_strategies/no_namespace.rb, lib/rom/setup/auto_registration_strategies/with_namespace.rb, rom.gemspec, spec/unit/rom/commands/pre_and_post_processors_spec.rb, spec/unit/rom/memory/dataset_spec.rb
One issue related to schema caching showed up after that.
=> Update dry-initializer to 1.3

lib/rom/auto_curry.rb, spec/unit/rom/auto_curry_spec.rb, spec/unit/rom/relation/lazy/combine_spec.rb
@solnic when I added this the specs started to fail because they had invalid expectations in `combine_spec.rb` :)
=> Yield block in curried methods

core/lib/rom/configuration_dsl.rb, core/lib/rom/configuration_dsl/relation.rb, core/lib/rom/relation.rb, core/lib/rom/relation/class_interface.rb, core/lib/rom/setup.rb, core/lib/rom/setup/finalize.rb, core/lib/rom/setup/finalize/finalize_relations.rb, core/spec/integration/commands/update_spec.rb, core/spec/integration/gateways/extending_relations_spec.rb, core/spec/integration/multi_env_spec.rb, core/spec/integration/relations/default_dataset_spec.rb, core/spec/integration/relations/inheritance_spec.rb, core/spec/integration/setup_spec.rb, core/spec/shared/command_graph.rb, core/spec/shared/container.rb, core/spec/unit/rom/container_spec.rb, core/spec/unit/rom/create_container_spec.rb, core/spec/unit/rom/plugin_spec.rb, core/spec/unit/rom/relation/map_with_spec.rb, core/spec/unit/rom/relation/schema_spec.rb, core/spec/unit/rom/relation_spec.rb, repository/spec/integration/typed_structs_spec.rb, repository/spec/shared/relations.rb, repository/spec/unit/changeset/associate_spec.rb
=> Replace register_as/dataset with schema

core/lib/rom/constants.rb, core/lib/rom/setup/finalize/finalize_mappers.rb, core/spec/integration/commands/create_spec.rb, core/spec/unit/rom/create_container_spec.rb
Solves #390 
Hope this is what we are looking for
=> Raise exception is user register mapper twice

mapper/lib/rom/mapper/builder.rb, mapper/spec/integration/setup_spec.rb
=> Added register_as when defining a mapper

core/lib/rom/command_compiler.rb, core/lib/rom/commands/graph.rb, core/lib/rom/initializer.rb, core/lib/rom/registry.rb, core/lib/rom/schema.rb, core/lib/rom/schema/inferrer.rb, mapper/lib/rom/mapper_compiler.rb
It's a kind of PoC, @solnic do you think it's a good idea to have `with` by default?
P.S. We cannot have it in dry-initializer because it has an API for renaming option keys
=> Auto-generate #with

lib/rom/types.rb, spec/unit/rom/relation/schema_spec.rb
Implement https://github.com/rom-rb/rom/pull/441 for `release-3.0`.
=> Generic JSON read/write type for release-3.0

core/lib/rom/relation.rb, core/spec/unit/rom/relation/combine_spec.rb
@solnic mind to test it? Works smooth on my side
=> Fix Relation#combine when using multi-key hashes

core/lib/rom/types.rb, core/spec/unit/rom/relation/schema_spec.rb
**Addressing**: https://github.com/rom-rb/rom/pull/446#discussion_r133506000 in context of `4.X`
Also see: #447
=> Types/coercible json naming change - 4.X

repository/lib/rom/repository/class_interface.rb, repository/spec/integration/command_macros_spec.rb, repository/spec/shared/relations.rb
=> Fix splatting args in command macros

lib/rom/types.rb
Cherry-pick of cb838f4
Fixes #457
=> Fix constant redefined warnings

core/lib/rom/memory/relation.rb, core/lib/rom/plugin_registry.rb, core/lib/rom/relation/class_interface.rb, core/lib/rom/schema.rb, core/lib/rom/schema/inferrer.rb
* Provides documentation for DSL methods
* Fixes incorrect YARD macros
=> Provide better documentation

core/lib/rom/relation.rb, core/lib/rom/relation/combined.rb, core/lib/rom/relation/composite.rb, core/lib/rom/relation/wrap.rb, core/spec/unit/rom/relation/lazy_spec.rb, core/spec/unit/rom/relation/map_to_spec.rb, core/spec/unit/rom/relation/map_with_spec.rb
=> [core] auto-map when auto_map? returns true

repository/lib/rom/repository/root.rb
Issue https://github.com/rom-rb/rom/pull/510#issuecomment-447844282
=> Add a deprecation warning for `Root#aggregate`

core/lib/rom/schema/associations_dsl.rb
I was going through the documentation and found these return values mentioned, that don't seem to be inline with the code.
=> Fix return values mentioned in documentation

core/lib/rom/mapper_compiler.rb
This uses same nomenclature of rom-rb/rom-sql#326
=> Explicit usage by naming of meta/options bag

core/lib/rom/attribute.rb, core/lib/rom/schema/dsl.rb, core/spec/unit/rom/relation/schema_spec.rb
=> Fix handling of attribute options

core/lib/rom/relation/combined.rb, core/spec/unit/rom/relation/combine_spec.rb, core/spec/unit/rom/relation/combined/combine_spec.rb
=> Fix Combined when the same node is provided more than once

changeset/lib/rom/changeset.rb, changeset/spec/integration/plugin_spec.rb
=> [changeset] add Plugin API

changeset/lib/rom/changeset/pipe.rb, changeset/lib/rom/changeset/pipe_registry.rb, changeset/lib/rom/changeset/stateful.rb, changeset/spec/unit/pipe_spec.rb
same as #572 but for the `5.2` release
=> [changeset] refactor pipe

changeset/lib/rom/changeset/update.rb
I think this way it won't break any existing code around.
=> Use explicit coercion in update changeset

core/lib/rom/plugins/command/schema.rb, core/spec/integration/commands/update_spec.rb
=> Fix duplicated input processing in update commands

.github/workflows/ci.yml, .github/workflows/custom/ci.yml
This sets up our CI to run against TruffleRuby.
Refs #549
=> [ci] truffleruby

.github/workflows/custom/ci.yml, Gemfile, docker-compose.yml, lib/rom/gateway.rb, lib/rom/repository.rb, lib/rom/repository/root.rb, lib/rom/transaction.rb, spec/spec_helper.rb, spec/unit/rom/repository/session_spec.rb, spec/unit/rom/repository/transaction_spec.rb
=> Add gateway option to Repository#transaction

lib/rom/environment.rb, lib/rom/gateway.rb, spec/integration/gateways/gateway_params_spec.rb
=> #622 Fix gateway configuration options

core/docsite/source/mappers.html.md
This pull request replaces the current usage example for custom mappers by one with a transforming pipeline and comments on what the functions in the pipeline do.
=> Improved usage example for custom mappers.

core/lib/rom/processor/transproc.rb
Hi 😃 
I want to use Transproc::Conditional, so I added it
=> Import Transproc::Conditional

core/docsite/source/relations.html.md
Noticed a space missing, quick change
=> Fix one indentation
