rom-rb/rom

lib/rom/repository.rb
Let's remove this - it's not used, but marked as public API and we're thinking about removing `Adapter#connection`.
=> Remove unused `connection` from Repository

lib/rom/setup/base_relation_dsl.rb
This method changes its behavior after the first call. It might not hurt
right now as `@repository` is always empty, but let's clean this up
anyways.
=> Simplify #repository in BaseRelationDsl

lib/rom/adapter/memory/storage.rb, rom.gemspec, spec/unit/rom/adapter/memory/storage_spec.rb
`ROM::Adapter::Memory::Storage` is currently not thread-safe which becomes an issue on JRuby and Rubinius.
=> Make storage in memory adapter thread safe

README.md
The rom-csv link is linking to the yaml repository, fixed it!
=> Update README rom-csv link

lib/rom/commands/result.rb, spec/unit/rom/commands/result_spec.rb
Do not allow ROM::Commands::Result#value to nest another instance of ROM::Commands::Result. Bubble up value to root.
=> bubble up nested values

lib/rom/lint/enumerable_dataset.rb, lib/rom/lint/linter.rb, lib/rom/lint/repository.rb
I'm really impressed by some of the ideas in ROM and it has been a lot of fun to play with writing extensions so far. While rapidly growing and stabilising, ROM (in its current state) is still a bit daunting for authors of adapters to get their heads around. I'd like to help improve that.
If these docs are okay, I'll start adding more patches here and there, and make some notes from the perspective of helping library authors get up to speed with what they need to do to plug all kinds of query APIs and dataset enumerators into ROM.
Let me know what you think.
=> Add basic docs for linters

Gemfile, lib/rom.rb, lib/rom/command.rb, lib/rom/model_builder.rb, lib/rom/reader.rb, lib/rom/relation.rb, lib/rom/setup_dsl/command.rb, lib/rom/setup_dsl/relation.rb, lib/rom/support/inflector.rb, spec/unit/rom/support/inflector_spec.rb
Drop hard dependency on Inflecto and use a simple detection mechanism to use ActiveSupport::Inflector if it's available. We still fall back to using Inflecto if not.
Fixes #156.
=> Hide inflections behind an internal interface

README.md, lib/rom/env.rb, lib/rom/relation/loaded.rb, lib/rom/support/enumerable_dataset.rb, spec/integration/relations/reading_spec.rb, spec/unit/rom/env_spec.rb, spec/unit/rom/relation/loaded_spec.rb
This does a couple of things:
- adds `ROM::Env#relation` that yields *relation object* to the block and returns an instance of `Relation::Loaded` it means that you have access to all methods exposed by a relation there including adapter-specific query DSL
- `Relation::Loaded` exposes `#map_with` interface that accepts name of a mapper that should be used
- `Relation::Loaded#map_with` supports multiple mapper names so we can map and decorate tuples passing them through a "mapping pipe", see my comment with an example in this PR
- the contract is that `map_with` can be called only once, it returns an array
- `ROM::Env#mappers` returns a registry of relation mappers that were defined during setup
Things to consider:
- Deprecate usage of Reader and remove it in 0.7.0 (or 1.0.0!) - I realized …
=> Add Relation::Loaded and use it in rom.relation {}

Gemfile, lib/rom/support/inflector.rb, rom.gemspec, spec/unit/rom/support/inflector_spec.rb
The `inflecto` gem is no longer a dependency.  If neither `activesupport` nor `inflecto` are available, the inflector API raises a `LoadError` informing the user that they should install an inflector backend.
I'm not entirely happy with having to introduce the `setup` method to `ROM::Inflector` and call it immediately, but it was the only obvious way to make it testable.  Suggestions on patterns for cleaning that up welcomed. :smile:
=> Remove `inflecto` from gemspec

README.md, benchmarks/basic.rb, benchmarks/setup.rb, lib/rom/constants.rb, lib/rom/env.rb, lib/rom/relation.rb, lib/rom/relation/composite.rb, lib/rom/relation/curried.rb, lib/rom/relation/lazy.rb, lib/rom/relation/loaded.rb, spec/integration/relations/reading_spec.rb, spec/shared/one_behavior.rb, spec/unit/rom/env_spec.rb, spec/unit/rom/relation/composite_spec.rb, spec/unit/rom/relation/lazy_spec.rb, spec/unit/rom/relation/loaded_spec.rb
This adds a new API on top of `Relation` called `Relation::Lazy` which provides following features:
* ability to treat relations as callable "function" objects
* ability to compose two relations with left-to-right data pipelining
* ability to pass relations through mappers using the same left-to-right data pipelining
* lazy relations support auto-curry so you can do things like `user_by_id = users.by_id; user_by_id[1]`
This new API is used when you access relations via `rom.relation(:rel_name)`:
``` ruby
users = rom.relation(:users) # returns lazy-users
entity_users = users.map_with(:entities)
entity_users = users.as(:entites)
entity_users.by_id(1)
entity_user_by_id = entity_users.by_id
entity_user_by_id[1]
```
=> Lazy-relation API

lib/rom/lint/linter.rb, lib/rom/lint/repository.rb
We are leaking connections in `rom-sql` during specs.
Linter could automatically call `Repository#disconnect` after each lint method run to avoid this leakage.
WDYT?
/cc @solnic @elskwid
=> Add hook methods to linter

lib/rom/memory/storage.rb
I see that the dependency on `thread_safe` was removed in 64f8171601753049d8b3c3b1524db58165c68d0e. It seems to there should be better error handling in the memory adapter now to make this dependency clearer.
Right now, if you try to use the memory adapter without `thread_safe`, this error is raised:
```
/[…]/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': \
cannot load such file -- thread_safe (LoadError)
```
With this patch applied, it looks like this:
```
/[…]/lib/rom/memory/storage.rb:4:in `rescue in <top (required)>': \
Please install the `thread_safe` gem. (LoadError)
```
=> Improve LoadError on missing thread_safe gem

Gemfile, lib/rom/command_registry.rb, lib/rom/commands/abstract.rb, lib/rom/commands/composite.rb, lib/rom/env.rb, lib/rom/support/registry.rb, spec/integration/commands/create_spec.rb, spec/spec_helper.rb
Basically making this work:
``` ruby
rom.command(:users).as(:entity).create[name: 'Jane']
```
=> Add support for mapping command results (refs #185)

lib/rom/command_registry.rb, spec/unit/rom/command_registry_spec.rb
The `0.6.1` release has broken the `respond_to?` method in the `CommandRegistry`.
This fixes it.
=> Fix CommandRegistry#respond_to?

spec/unit/rom/memory/dataset_spec.rb
The original test wasn't asserting that sorted values were being returned in any particular order. This happens because `#match_array` is simply checking the values in the array, not the specific ordering of the data structure (this is probably why `#match_array` has been aliased to the more meaningful `#contain_exactly` in more recent versions of Rspec).
You can verify this by running the following, which should fail, but passes:
```ruby
describe '#order' do
it 'sorts data using provided attribute names' do
expect(dataset.order(:name)).to match_array([
{ name: 'Jade', email: 'jade@doe.org', age: 11 },
{ name: 'Jane', email: 'jane@doe.org', age: 10 },
{ name: 'Joe', email: 'joe@doe.org', age: 12 }
])
end
it 'ignores order of array values in comparison' do
expect(dataset.order(:name)).to …
```
=> Use #eq instead of #match_array to test memory adapter #order

lib/rom/mapper/attribute_dsl.rb, lib/rom/processor/transproc.rb, spec/integration/mappers/overwrite_attributes_value_spec.rb
In block you can overwrite attribute value, or modify it:
```ruby
attribute :foo do 'John' end
attribute :foo do |t| t.upcase end
attribute :foo, from: :bar do 1+2 end
```
=> Allow to define block in mapper attribute

lib/rom/mapper/attribute_dsl.rb, spec/integration/mappers/group_spec.rb
This is a fix for the case a group has just the same name as one of its fields.
```ruby
class UsersMapper < ROM::Mapper
group agenda: [:agenda]
end
```
Badly needs for somebody to review it!
=> Allow grouping attributes with the name of existing field:

lib/rom/memory/dataset.rb, spec/unit/rom/memory/relation_spec.rb
```ruby
relation.restrict(id: [1,2,3,4])
```
=> Allow to call `#restrict` with array as value

lib/rom/memory/dataset.rb, spec/unit/rom/memory/relation_spec.rb
Allow restrict to be called will regexp.
```ruby
relation.restrict(name: /\w{4}/)
```
=> Extend `#restrict`

CHANGELOG.md, Gemfile, lib/rom/header/attribute.rb, lib/rom/mapper/attribute_dsl.rb, lib/rom/processor/transproc.rb, rom.gemspec, spec/integration/mappers/fold_spec.rb
Addressing #199, #200 and #220
The `fold` is a kind of group that provides array of values, extracted
from a first attribute of grouped tuples:
```ruby
users.with_tasks.to_a
class UsersMapper < ROM::Mapper
attribute :name
fold tasks: [:task]
end
users.as(:users).to_a
```
Unlike `group` the `fold` doesn't support block syntax and nesting.
=> Add 'fold' feature to AttributeDSL

lib/rom/mapper/attribute_dsl.rb
Noticed the `unwrap` method has no inline docs.
Maybe there was any reason for that?
=> Add inline docs for `unwrap` mapper operation

lib/rom/mapper/attribute_dsl.rb, spec/integration/mappers/reusing_mappers_spec.rb, spec/unit/rom/mapper/dsl_spec.rb
- `AttributeDSL#embedded` allows `options[:type]` to be overwritten when `options[:mapper]` is passed in.
Example:
```ruby
class EntryMapper < ROM::Mapper
attribute :id, type: :integer
end
class EntriesMapper < ROM::Mapper
embedded :data, type: :hash, mapper: EntryMapper
end
tuples =  [{
data: {
id: '10'
}
}]
EntriesMapper.build.call(tuples)
```
=> Fix nested mappers when used with #embedded and type: hash

lib/rom/commands/abstract.rb, lib/rom/commands/graph.rb, lib/rom/commands/graph/class_interface.rb, lib/rom/commands/lazy.rb, lib/rom/env.rb, lib/rom/memory/commands.rb, spec/integration/commands/graph_builder_spec.rb, spec/integration/commands/graph_spec.rb, spec/unit/rom/commands/lazy_spec.rb, spec/unit/rom/env_spec.rb
=> Add Commands::Graph.build and extend `Env#command` to support it

lib/rom/header.rb, lib/rom/mapper/attribute_dsl.rb, spec/integration/mappers/unwrap_spec.rb, spec/unit/rom/processor/transproc_spec.rb
Example:
```ruby
unwrap :contact, from: :user do
attribute :name
end
user.first
user.as(:users).first
```
Also applied to `ungroup` (yet uncovered).
=> Fix `unwrap` to allow renaming the rest of wrapped attribute

lib/rom/header.rb, lib/rom/header/attribute.rb, lib/rom/processor/transproc.rb, spec/unit/rom/processor/transproc_spec.rb
Ogres are like onions:
```ruby
unwrap :contact do
unwrap :email
attribute :email, from: :address
end
end
users.first
users.as(:users).first
```
think, `unwrap` is ready. 
I have plans for `ungroup` (slightly more coverage), `prefix` and `exclude`, but not sure this is for 8.0.0
=> Fix `unwrap` to deal with deep nesting

lib/rom/header/attribute.rb, lib/rom/mapper/attribute_dsl.rb, lib/rom/processor/transproc.rb, spec/integration/mappers/definition_dsl_spec.rb, spec/integration/mappers/exclude_spec.rb
Renamed old `exclude` to `remove` and made it private. Implemented the `exclude` as a special type of attribute that removes key.
This allows using `exclude` from the root, so now we can either whitelist (with `reject_keys`) or blacklist (with `exclude`) attributes.
```ruby
class UserMapper < ROM::Mapper
relation :users
register_as :users
exclude :password
end
```
=> Support `exclude` attribute from root

lib/rom/mapper/attribute_dsl.rb, spec/unit/rom/mapper/dsl_spec.rb
When I was perusing the docs I came across [these](https://github.com/rom-rb/rom-rb.org/blob/guides/source/doc-pages/guides/basics/mappers/wrapping.md#edge-cases-1):
> Don't define attributes inline along with the :mapper option! In this case the mapper won't be applied:
and 
> Don't use block along with the :mapper option! All definitions from inside the block will be ignored:
Instead of using documentation to let a developer know about a potential misuse I think it'd be better if the code told the dev. Plus this way it'll fail faster and the dev won't have figure out why his/her mapper isn't being used.
=> Raise errors when configuring a mapper ambiguously

.rubocop.yml, benchmarks/setup.rb, lib/rom/command.rb, lib/rom/pipeline.rb, lib/rom/relation/class_interface.rb, spec/integration/mappers/group_spec.rb, spec/integration/multi_repo_spec.rb, spec/shared/materializable.rb, spec/unit/rom/mapper_spec.rb, spec/unit/rom/relation/lazy/combine_spec.rb
* ignore vendored files
* removed `Blocks` section
* removed RegexpLiteral section
* added MultilineOperationIndentation section
* ~~Align operands in multi-line assignments~~
* _Indent_ operands in multi-line operation chains
* Modify arguments to indicate if they won't be used
* Remove parallel assignment
* Add a space inside curly braces for blocks
* Remove extra line from block body beginning
* Use Array#size instead of Array#count
* Replace {} with do/end for procedural block
* Remove semicolon as expression terminator
* _added `MultilineOperationIndentation` section_
* _Indent operands in multi-line operation chains_
* _rebased on top of master to fix merge conflicts_
* _created a new pull request_
=> Cleanup a few rubocop offenses

spec/integration/mappers/group_spec.rb
This feature cannot be supported because grouping to the existing key
is treated like updating the existing group.
```ruby
group email: [:email] # not supported (can cause undesired results)
```
=> Removed support for grouping under the same name as one of keys

spec/unit/rom/memory/commands/create_spec.rb, spec/unit/rom/memory/commands/delete_spec.rb
The `unit/rom/memory/commands/create_spec.rb` and
`unit/rom/memory/commands/delete_spec.rb` were reversed;
`create_spec.rb` tested the Delete command and `delete_spec.rb` tested
the Create command.
Reverse the filenames.
=> Fix memory's create/delete unit tests

README.md
The current ‘Guides’ link in the README links to the introduction; this makes it link to guides. :)
=> README: link Guides properly

lib/rom.rb, lib/rom/command.rb, lib/rom/commands/graph/class_interface.rb, lib/rom/container.rb, lib/rom/environment.rb, lib/rom/environment/plugin_dsl.rb, lib/rom/environment_plugin.rb, lib/rom/environment_plugins/auto_registration.rb, lib/rom/global.rb, lib/rom/global/plugin_dsl.rb, lib/rom/mapper.rb, lib/rom/plugin.rb, lib/rom/plugin_base.rb, lib/rom/plugin_registry.rb, lib/rom/relation.rb, lib/rom/relation/class_interface.rb, lib/rom/relation_registry.rb, lib/rom/setup.rb, lib/rom/setup/finalize.rb, lib/rom/support/guarded_inheritance_hook.rb, lib/rom/support/inheritance_hook.rb, lib/rom/support/publisher.rb, rom.gemspec, spec/spec_helper.rb, spec/unit/rom/container_spec.rb, spec/unit/rom/setup_spec.rb
This PR removes the auto-registration on inherited hooks and is a step towards removing the ROM global interface, allowing for multi-env and removing a lot of the global state. Auto-registration can still be achieved as @krisleech's `wisper` broadcasts `inherited` messages on the relevant class (`ROM::Relation`, `ROM::Mapper`, `ROM::Command`) when inherited.
```ruby
rom = ROM::Environment.new
rom.setup(:memory)
class Users < ROM::Memory::Relation
dataset :users
end
class UserMapper < ROM::Mapper
relation :users
register_as :entity
model Struct.new(:id, :name)
attribute :id
attribute :name
end
class CreateUser < ROM::Memory::Commands::Create
relation :users
register_as :create
result :one
end
rom.register_relation(Users)
rom.register_mapper(UserMapper)
rom.register_command(CreateUser) …
```
=> ROM::Global => ROM::Environment (multi-env)

lib/rom/relation/class_interface.rb
According to this benchmark [1] tr is way faster compared to gsub
especially when just replacing a single character.
[1]: https://github.com/JuanitoFatas/fast-ruby#stringgsub-vs-stringtr-code
=> Use tr instead of gsub

spec/unit/rom/relation_spec.rb
I don't know if this is somehow useful (because as the deprecation warning explains, it will be removed in v1.0.0). I guess I chose a bad method to start killing mutants, switching to useful ones (in another branch) now ;)
Anyways, this PR reduces the number of alive mutants from 32 to 16 (@ ROM::Relation)
=> Kill 16 alive mutants @ ROM::Relation

lib/rom/gateway.rb, lib/rom/memory/gateway.rb, spec/unit/rom/gateway_spec.rb
class ROM::CustomAdapter::Gateway < ROM::Gateway
adapter :custom_adapter
end
ROM::CustomAdapter::Gateway.adapter     # => :custom_adapter
ROM::CustomAdapter::Gateway.new.adapter # => :custom_adapter
Also added `adapter :memory` setting to memory adapter.
The `.adapter` is not required for backward-compatibility.
But if it hasn't been set, then calling `#adapter` (instance method) will
raise the exception.
ROM::ImperfectAdapter::Gateway = Class.new(ROM::Gateway)
ROM::ImperfectAdapter.new.adapter
== Added
* ROM::Gateway extends ROM::Support::ClassMacros
* ROM::Gateway.adapter (getter/setter)
* ROM::Gateway#adapter (getter only)
=> Add adapter setting to Gateway

lib/rom/commands/abstract.rb, lib/rom/commands/graph/class_interface.rb, lib/rom/commands/lazy.rb, lib/rom/commands/lazy/create.rb, lib/rom/commands/lazy/delete.rb, lib/rom/commands/lazy/update.rb, spec/integration/commands/graph_spec.rb, spec/unit/rom/commands/lazy_spec.rb
This is a failing spec to demonstrate #312 
There are a couple of things that end up happening here;
Most notably, there's no particular way to actually filter the remove
commands, so the first failure case ends up removing _all_ tasks.
This can arguably be fixed from within the execute method of the remove
task, but most command bases don't provide an easy way to _internally_
modify the relation that gets used by the execute method.
There's a related filtering problem where updates are concerned, which
should be exercised and demonstrated by this spec as well, but the
specific failure is masked by the unfiltered delete.
=> [REPRO] set up failing acceptance spec for update commands

lib/rom/setup/auto_registration.rb
It appears to be expecting so, as '#dirname' is called on it further down.
=> Make @directory a Pathname always

Gemfile, lib/rom/memory/storage.rb, rom.gemspec
Keep in mind that concurrent-ruby is a dry-t dependency.
=> Replace thread_safe with concurrent-ruby in memory storage

lib/rom/setup.rb, lib/rom/setup/auto_registration.rb, lib/rom/setup/auto_registration_strategies/base.rb, lib/rom/setup/auto_registration_strategies/custom_namespace.rb, lib/rom/setup/auto_registration_strategies/no_namespace.rb, lib/rom/setup/auto_registration_strategies/with_namespace.rb, spec/fixtures/custom/commands/create_user.rb, spec/fixtures/custom/mappers/user_list.rb, spec/fixtures/custom/relations/users.rb, spec/unit/rom/auto_registration_spec.rb
Referencing issue #353 
I added ability to register namespaces via string and moved constant creation to strategies. Few questions:
* ~~Is it okay to use kw args or should I use Options module here?~~
* Should I move internal classes to separate files?
* Is the strategy approach okay here?
One benefit I see with strategies, that we can later pass our own to make it even more customisable as mentioned in #353 
Let me know what you thin and Ill be happy to adjust the code
**EDIT:**
I see that test suite expects Ruby 2.0, so changed the strategy classes to use ROM Options module
=> Added ability to define custom namespace with String

Gemfile, lib/rom.rb, lib/rom/association_set.rb, lib/rom/command.rb, lib/rom/commands/class_interface.rb, lib/rom/commands/composite.rb, lib/rom/configuration_dsl.rb, lib/rom/configuration_dsl/command.rb, lib/rom/configuration_dsl/mapper.rb, lib/rom/configuration_dsl/mapper_dsl.rb, lib/rom/configuration_dsl/relation.rb, lib/rom/constants.rb, lib/rom/global.rb, lib/rom/global/plugin_dsl.rb, lib/rom/plugins/configuration/configuration_dsl.rb, lib/rom/plugins/relation/key_inference.rb, lib/rom/relation/class_interface.rb, lib/rom/schema.rb, lib/rom/setup/auto_registration.rb, lib/rom/setup/auto_registration_strategies/custom_namespace.rb, lib/rom/setup/auto_registration_strategies/no_namespace.rb, lib/rom/setup/auto_registration_strategies/with_namespace.rb, rom.gemspec, spec/spec_helper.rb
As a part of [leaving rom-support behind](https://github.com/dry-rb/dry-types/pull/132) I added dry-core to rom's dependencies and started to use its modules where possible.
=> Add dry-core as a dependency

lib/rom/plugins/relation/view.rb, lib/rom/plugins/relation/view/dsl.rb, lib/rom/relation/class_interface.rb, lib/rom/schema.rb, lib/rom/setup/finalize/finalize_relations.rb, spec/unit/rom/plugins/relation/view_spec.rb
This will add a couple of sweet new features:
=> feature: schemas in view definitions

lib/rom/schema.rb, lib/rom/schema/type.rb, spec/spec_helper.rb, spec/support/schema.rb, spec/unit/rom/schema/project_spec.rb, spec/unit/rom/schema/rename_spec.rb
This makes `Schema#project` first class and adds `Schema#rename`. We'll be able to replace `header` concept in rom-sql with this (header will be deprecated there).
=> Feature: schema projection api

lib/rom/command.rb, lib/rom/commands/class_interface.rb, lib/rom/commands/lazy/create.rb, lib/rom/commands/lazy/update.rb, spec/integration/commands/create_spec.rb, spec/integration/commands/graph_spec.rb, spec/shared/command_graph.rb, spec/unit/rom/commands/graph_spec.rb, spec/unit/rom/commands/lazy_spec.rb, spec/unit/rom/commands/pre_and_post_processors_spec.rb, spec/unit/rom/commands_spec.rb
⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️  **BREAKING CHANGE** ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️ ⚠️
This makes it impossible to override `execute` to pre/post process input tuples, and makes `execute` a true implementation detail in adapters. This approach turned out to be problematic as we had to create additional command classes, configuring them was awkward, and it was inflexible. Instead of overidding `execute` this PR introduces a new concept of before/after hooks that are applied with correct arguments and in correct order.
This addition means two things:
- there's no longer any need to override `execute` (which was private anyway) in order to pre- or post-process input or result tuples
- hooks are based on class-level pre-configured options, or instance-level options that can be used at run-time
- …
=> Add before/after command hooks

lib/rom/plugins/command/schema.rb, lib/rom/relation.rb, lib/rom/schema.rb, lib/rom/schema/dsl.rb, lib/rom/schema/type.rb, spec/unit/rom/plugins/command/schema_spec.rb, spec/unit/rom/relation/call_spec.rb, spec/unit/rom/relation/schema_spec.rb, spec/unit/rom/relation_spec.rb
This extends schema DSL with the ability to define "read" type that will
be used when a relation loads its tuples. By default we set this to a
noop passthrough-proc but if there are any attributes with a special
"read" type then we use relation's schema "relation hash" which is built
from schema attributes including "read" types.
This is a last-moment addition but it turned out we can't support
various custom DB types without this feature, and it was planned already
for rom 3.1.0 anyway.
Here's extended schema API:
``` ruby
class Users < ROM::Relation[:yaml]
schema do
attribute :id, Types::String, read: Types::Coercible::Int
attribute :name, Types::String
end
end
```
/cc @flash-gordon @AMHOL
=> Add support for defining schema types for reading data

lib/rom.rb, lib/rom/configuration.rb, lib/rom/configuration_dsl.rb, lib/rom/create_container.rb, lib/rom/plugin.rb, lib/rom/plugin_base.rb, lib/rom/plugins/relation/instrumentation.rb, lib/rom/setup.rb, lib/rom/setup/finalize.rb, lib/rom/setup/finalize/finalize_relations.rb, lib/rom/support/configurable.rb, spec/integration/setup_spec.rb, spec/unit/rom/plugins/relation/instrumentation_spec.rb
This adds a new configuration dsl for setting up plugins with their config and a new relation plugin called `:instrumentation` which provides basic infrastructure for setting up instrumentation in adapters. This will be used in rom-sql to provide SQL logging.
=> Instrumentation plugin

lib/rom/setup/auto_registration.rb, lib/rom/setup/auto_registration_strategies/base.rb, lib/rom/setup/auto_registration_strategies/custom_namespace.rb, spec/fixtures/custom_namespace/commands/create_customer.rb, spec/fixtures/custom_namespace/mappers/customer_list.rb, spec/fixtures/custom_namespace/relations/customers.rb, spec/fixtures/wrong/commands/create_customer.rb, spec/fixtures/wrong/mappers/customer_list.rb, spec/fixtures/wrong/relations/customers.rb, spec/spec_helper.rb, spec/unit/rom/setup/auto_registration_spec.rb
Hello ROM people.
Some time ago I wanted to autoload some namespaced `ROM::Relation` I have had defined in my project and while everything looked fine and according to namespace path, I was surprised when this did not quite work out.
After some searching and asking on the gitter, I decided to take a look at the code (duh) and figured out autoloader takes only `File.basename(file, ".rb")` as constant name. So, in order to have everything working properly, I could not use `autoload(namespace: "Persistance")` with:
```ruby
module Persistance
module Relation
module Users < ROM::Relation[:sql]
end
end
end
```
... as this would attempt to load `Persistence::Users` instead of `Persistence::Relation::Users` and that, of course, would fail. Now, after I figured this out, I modified my code so it …
=> Expand AutoRegistrationStrategies::CustomNamespace

core/lib/rom/relation.rb, core/lib/rom/relation/wrap.rb, core/lib/rom/relation/wrap_methods.rb, repository/spec/unit/relation_proxy_spec.rb
This adds an explicit representation of a relation which embeds data from other relation(s). It's similar to `Relation::Graph` except that it's materialization logic may differ across adapters. There's a `remove-auto-wrap` branch in rom-sql where this was already integrated.
=> Introduce Relation::Wrap

core/lib/rom/associations/abstract.rb, core/lib/rom/associations/many_to_many.rb, core/lib/rom/associations/many_to_one.rb, core/lib/rom/associations/one_to_many.rb, core/lib/rom/associations/one_to_one.rb, core/lib/rom/associations/one_to_one_through.rb, core/lib/rom/relation.rb, core/lib/rom/relation/class_interface.rb, core/lib/rom/schema.rb, core/lib/rom/schema/associations_dsl.rb, core/lib/rom/schema/dsl.rb
This adds core associations APIs, including:
- `Schema::AssociationDSL`
- `Schema::DSL#associations` known from rom-sql
- `Associations::*` classes imported from rom-sql with sql-specific methods removed
- Ability to configure `Relation.schema_attr_class` which defaults to `Schema::Attribute` (and ie rom-sql sets this to `SQL::Attribute`
- A generic `Schema::DSL#call` method so that adapters don't have to implement it
I'll import specs from rom-sql later on. I want to remove ad-hoc combines first because it will simplify code.
=> Core associations

core/lib/rom/associations/abstract.rb, core/lib/rom/associations/definitions/abstract.rb, core/lib/rom/memory/associations.rb, core/lib/rom/memory/associations/many_to_many.rb, core/lib/rom/memory/associations/many_to_one.rb, core/lib/rom/memory/associations/one_to_many.rb, core/lib/rom/memory/associations/one_to_one.rb, core/lib/rom/memory/schema.rb, core/lib/rom/relation.rb, repository/spec/integration/multi_adapter_spec.rb
This adds a new feature which was required to make cross-adapter
associations work, which is `override` option in association DSL. If
it's set to `true` then a given association will not produce its own
relation and will use provided `:view` instead. This way we are
completely free to define association views however we want. These views
will receive both association object and loaded relation, which should
make it more flexible.
=> Enable cross-gateway associations

core/lib/rom/configuration.rb, core/lib/rom/create_container.rb, core/lib/rom/gateway.rb, core/lib/rom/relation/class_interface.rb, core/lib/rom/schema.rb, core/lib/rom/setup.rb, core/lib/rom/setup/finalize.rb, core/lib/rom/setup/finalize/finalize_commands.rb, core/lib/rom/setup/finalize/finalize_relations.rb, core/lib/rom/support/notifications.rb, core/spec/integration/commands_spec.rb, core/spec/unit/rom/gateway_spec.rb, core/spec/unit/rom/relation/view_spec.rb, core/spec/unit/rom/setup/auto_registration_spec.rb
This adds an event bus for configuration/finalization events. This way we can decouple core setup/config/finalization code from extensions and provide a robust API for hooking into rom-rb booting process.
This is divided into 3 parts:
- `ROM::Notifications` extension which can be used by anything to register events
- `ROM::Notifications::Listener` extension which can be used by anything to register event listeners
- `ROM::Notifications::EventBus` which is **instantiated** for every configuration, which means we don't use global listeners
Now, `ROM::Configuration` is now a publisher which registers a bunch of configuration events, it passes its notifications instance down to setup/finalize objects, and they trigger various events in correct moments.
We already have a couple of listeners:
- …
=> Refactor setup/finalize to use notifications

changeset/Gemfile, core/Gemfile, core/lib/rom/relation/class_interface.rb, core/lib/rom/schema.rb, core/lib/rom/schema/inferrer.rb, core/spec/support/schema.rb, core/spec/unit/rom/relation/view_spec.rb, core/spec/unit/rom/relation_spec.rb, core/spec/unit/rom/schema/finalize_spec.rb, repository/Gemfile, repository/spec/spec_helper.rb
This add ability to infer more than just attributes. In rom-sql we need this for indexes and foreign at least. In theory, we might infer some storage options as well, such as tablespaces and page fillfactor (or give an API for doing this).
=> Add default schema inferrer

core/lib/rom/constants.rb, core/lib/rom/relation/class_interface.rb, core/spec/unit/rom/relation_spec.rb
Solves #434 
@solnic after playing with the code I found this to be a good place for raising the error 😄 
Although the test infers the name from the `schema` macro I would have liked to test creating a `Relations` class but not under the namespace of `Test` but the `ConstantLiker` wouldn't allow me.
Hope this helps.
=> Raise exception for invalid relation name

core/lib/rom/setup/finalize/finalize_mappers.rb, core/spec/unit/rom/create_container_spec.rb
@solnic, as we discuss the MapperAlreadyDefinedError, must be scope to relations
=> Scope MapperAlreadyDefinedError error to relations.

core/lib/rom/schema/dsl.rb, core/spec/unit/rom/relation/schema_spec.rb
rom-sql's inferrer already does it automatically, without it things aren't working smoothly enough, for instance `attribute :email, Types::PG::Array(:varchar).optional` doesn't get converted from Sequel::PGArray to a plain Array value even the source type Types::PG::Array has a read type inside. Now it's possible not to bother about this nuances, though we might change the DSL/behavior in future (to make it easier/transparent of course).
=> Build optional read types in SchemaDSL

core/lib/rom/relation.rb, core/lib/rom/setup/finalize/finalize_relations.rb, core/spec/integration/multi_env_spec.rb, core/spec/unit/rom/relation/name_spec.rb
It turned out associations are now shares relations which is not as good as just sharing schemas. For instance, my app has two containers that use the same set of relations but different DB connections underneath, this leads to a situation where one relation tries to pull data through a different connection.
=> Build a separate schema for every container

core/lib/rom/types.rb, core/spec/unit/rom/relation/schema_spec.rb
Hi, following suggestion on Gitter, https://gitter.im/rom-rb/chat?at=597fb669210ac269204184f4
I would like to propose a generic json read/write type: `Coercible::Json` together with:
- `Coercible::Json()`
- `Coercible::JsonHash()`
- `Coercible::HashJson()`
=> Generic JSON read/write type

Gemfile
This is required since rom-rb/rom-sql@4746e546dee81895e9c88c6fad44f047316730ff increased the minimum required dry-types version for rom-sql to one that hasn't been released yet.
=> Use dry-types HEAD

core/lib/rom/schema.rb, core/spec/unit/rom/relation_spec.rb
I think `Schema.definition` already worked correctly before, until we lost `attr_class` agrument for schema initilazer [here](https://github.com/rom-rb/rom/commit/c7518fc28#diff-3ac454f9c196d0f7c33922c20f51583cL117).
It also is reason of #460
=> Fix ROM::Schema.define method

Gemfile, mapper/lib/rom/struct.rb, mapper/spec/unit/rom/struct_compiler_spec.rb
Otherwise, it conflicts with the latest dry-struct and the did_you_mean gem in a really weird way.
=> Make error messages about missing attribute lazy

core/lib/rom/schema.rb, core/lib/rom/setup/finalize/finalize_relations.rb, core/spec/integration/setup_spec.rb
@solnic @flash-gordon 
I created this PR so we can discuss this https://github.com/rom-rb/rom-sql/issues/247. The finalize process still quite complex and I'm sure I'm missing something.
For what it looks like at this point when this message `configuration.relations.registry.created` is trigger the `RealtionRegistry` has been created. 
So I thought might be a simple solution to set the relations for each schema at this point.
=> [core] set relation registry in schema upon finalization

Gemfile, core/lib/rom/associations/definitions/abstract.rb, core/lib/rom/associations/through_identifier.rb, core/lib/rom/command_compiler.rb, core/lib/rom/command_proxy.rb, core/lib/rom/commands/class_interface.rb, core/lib/rom/configuration_dsl/command.rb, core/lib/rom/configuration_dsl/relation.rb, core/lib/rom/gateway.rb, core/lib/rom/relation.rb, core/lib/rom/relation/class_interface.rb, core/lib/rom/schema/associations_dsl.rb, core/lib/rom/setup/auto_registration.rb, core/lib/rom/setup/auto_registration_strategies/custom_namespace.rb, core/lib/rom/setup/auto_registration_strategies/no_namespace.rb, core/lib/rom/setup/auto_registration_strategies/with_namespace.rb, core/lib/rom/support/inflector.rb, core/spec/support/schema.rb, mapper/lib/rom/model_builder.rb, mapper/lib/rom/struct_compiler.rb
We're switching to dry-inflector as THE inflection backend in rom-rb. Usage of `Dry::Core::Inflector` is removed.
=> Use dry-inflector

core/lib/rom/command_compiler.rb, core/lib/rom/commands/class_interface.rb, core/lib/rom/core.rb, core/lib/rom/plugin.rb, core/lib/rom/plugins/command/timestamps.rb, core/lib/rom/relation/commands.rb, core/spec/unit/rom/command_compiler_spec.rb, core/spec/unit/rom/plugins/command/timestamps_spec.rb, repository/lib/rom/repository/class_interface.rb, repository/spec/integration/command_macros_spec.rb, repository/spec/shared/plugins.rb
Solves #467 
- Allow to pass options to command plugins
- Refactor Command Timestamp plugin to accept options
- Move Command Timestamp plugin to rom-core
After this changes the `timestamp` plugin will works as before and also accepts initial options to set timestamps.
```ruby
class CreateTask < ROM::Commands::Create[:sql]
result :one
use :timestamps, timestamps: %i(created_at, updated_at), datestamps: %i(:written)
end
```
Also in order to been able to set a fully working command from a `Relation` we need to allow passing options to the `commands` API, since we support setting multiple commands, I decided to go with the approach of having a new argument `plugins_options` been a hash where each key must be equal to the plugins name.
```ruby
class UserRepo < ROM::Repository[:users]
commands …
```
=> Allow options for command timestamps plugin

core/lib/rom/schema/associations_dsl.rb
The RDocs are for the method #has_one, but the examples are showing #one_to_one, so we fix that.
=> Fix RDoc example for #has_one

changeset/spec/integration/changeset_spec.rb, core/lib/rom/command.rb, core/lib/rom/plugins/command/timestamps.rb
Changesets pass themselves as an argument to command pipelines, rather
than the raw tuple.  Because the timestamp plugin was using Hash/Array
to determine the method to use for blending new data, it was triggering
a failure when the changeset fell through the case statement here.
We should probably keep an eye out for any similar patterns in command
hooks as the resulting error message was an utterly unclear:
ArgumentError:
wrong number of arguments (given 0, expected 1)
fixes #475
=> Make timestamp plugin work with changesets

core/lib/rom/setup/auto_registration_strategies/custom_namespace.rb, core/spec/unit/rom/setup/auto_registration_spec.rb
In my app, I have `App::Events` which is a module not related to the persistence layer and I also have `App::Relations::Events` which is a relations class. `CustomNamespace` wrongfully picks up `App::Events` rather than App::Relations::Events. This PR fixes the issue, now it starts with the longest constant name.
=> Look up the most nested constant first in the CustomNamespace strategy

core/lib/rom/relation/class_interface.rb, core/spec/unit/rom/relation/schema_spec.rb
Fixes ":plugin doesn't exist in ROM::AdapterPluginRegistry registry"
when using adapter-specific plugins.
=> Provide adapter to schema DSL instance

core/lib/rom/relation/class_interface.rb, core/spec/unit/rom/relation/schema_spec.rb
Reverts rom-rb/rom#480
This broke `rspec ./spec/integration/setup_spec.rb:44 # Setting up rom suite configuring plugins for schemas extends schema dsl` so it needs more work.
=> Revert "Provide adapter to schema DSL instance"

changeset/lib/rom/changeset/pipe.rb, changeset/spec/unit/pipe_registry_spec.rb
There was no way to override timestamps when using the `:add_timestamps` and `:touch` [transformations](http://rom-rb.org/4.0/learn/core/changesets/#changeset-mapping) with changesets.
I discussed it with @flash-gordon and decided to open a PR to add the possibility. I added tests and tried to follow the conventions, but let me know if anything is missing.
Edit: opened a [pull request](https://github.com/rom-rb/rom-rb.org/pull/255) to rom-rb.org as well.
=> Allow specifying timestamps manually when using mappers

changeset/spec/integration/changeset_spec.rb
I was reading tests and payed attention to unused `let` statement. Git history hints that it should be removed.
=> Cleanup tests: remove unused statement

changeset/spec/spec_helper.rb, repository/spec/spec_helper.rb
This is based on the following issue in Truffleruby https://github.com/oracle/truffleruby/issues/1470 and suggested by @eregon.
It's better to check availability of `Warning` module if given Ruby interpret has it rather than checking only Ruby version.
The latest Truffleruby 1.0.0-rc9 claims to be compatible with Ruby 2.4. Unfortunately, it doesn't contain `Warning` module yet.
=> Better Warning module detection in spec_helper.rb

.dockerignore, Dockerfile, changeset/spec/spec_helper.rb, docker-compose.yml, repository/spec/spec_helper.rb
I created this PR while preparing my environment to contribute in another PR.
This sets up a docker environment ready to start contributing to rom. I think that for a library like this one, which has system dependencies (sqlite dev tools), uses external services (postgres) and expects a given configuration (database url) it can be quite helpful. With it, you can just clone rom repo and do:
1. `docker-compose up -d`
2. `docker-compose exec app bundle exec rake spec`
I had to modify spec helper files in order to allow them to take database uri from the docker defined environment, but local development should behave as before.
If you find it useful and you want maybe I could add another commit modifying the README or CONTRIBUTING files?
=> Add docker development environment

Dockerfile, docker-compose.yml, docker_start.sh
- Ready to use without Gemfile.lock
- Cache pre-installed gems when bundle install
- Simplify Dockerfile
=> Improve docker environment

core/lib/rom/relation/combined.rb, core/spec/unit/rom/relation/combined/method_missing_spec.rb
When the response from a forwarded method call returns another combined
relation, we need to merged nodes and return a new combined relation.
Otherwise we were loosing previously combined nodes.
Fixes #525
=> [core] fix forwarding to root in Relation::Combined

repository/lib/rom/repository.rb, repository/lib/rom/repository/class_interface.rb, repository/spec/integration/plugin_spec.rb
Depends on #545 
Example usage:
```ruby
module NullifyPlugin
def self.apply(target, _options)
target.prepend(self)
end
def set_relation(*)
super.where { `1 = 0` }
end
end
ROM.plugins do
register :nullify_datasets, NullifyPlugin, type: :repository
end
class UserRepo < ROM::Repository[:users]
use :nullify_datasets
end
```
=> Add support for repository plugins

changeset/rom-changeset.gemspec, core/rom-core.gemspec, repository/rom-repository.gemspec, rom.gemspec
RubyGems.org website doesn't support editing gem links manually anymore,
but these links can be added to gemspec metadata, and RubyGems.org will
automatically pick them up.
=> Add links to the RubyGems.org gem pages

core/lib/rom/transformer.rb, core/spec/integration/transformer_spec.rb
This adds a `Transformer.map` shortcut which uses the new `define!` DSL from transproc 1.1.0 - when a transformer is defined using `map`, you will be able to use instance methods too. Furthermore `relation` now accepts `:as` option that will set `register_as`.
=> [core] improve transformer

changeset/lib/rom/changeset.rb, changeset/lib/rom/changeset/stateful.rb, changeset/spec/integration/command_options_spec.rb, changeset/spec/shared/database.rb
This adds support for configuring changeset commands using `command_options` and `command_plugins` class settings.
Here's what will be possible with this feature:
```ruby
module TimestampPlugin
def self.apply(klass, options)
klass.command_plugins :timestamps, timestamps: options
end
end
ROM::Plugins.register(:timestamp, TimestampPlugin, type: :changeset)
class CreateChangeset < ROM::Changeset::Create
use :timestamps, [:created_at]
end
```
=> [changeset] support for command options and plugins

core/lib/rom/constants.rb, core/lib/rom/registry.rb, core/lib/rom/schema/associations_dsl.rb, core/spec/unit/rom/association_set_spec.rb, core/spec/unit/rom/schema/associations_dsl_spec.rb
Previously:
```
> users.associations[:foo]
ROM::ElementNotFoundError: :foo doesn't exist in ROM::AssociationSet registry
```
Now:
```
> users.associations[:foo]
ROM::ElementNotFoundError: :foo doesn't exist in ROM::AssociationSet[:users] registry
```
=> [core] better association set exceptions

core/lib/rom/relation/name.rb, core/spec/unit/rom/relation/name_spec.rb
Previously equalizing relation names would skip checking `key` attribute, which is used when a relation is aliased. This is common when using associations with custom names, in such cases a relation is aliased.
Refs #562
=> [core] fix Relation::Name equality

core/lib/rom/relation/combined.rb, core/spec/integration/mapper/combine_spec.rb, core/spec/unit/rom/relation/combine_with_spec.rb
Refs #548 
It turned out using `Relation#eql?` (which is based on `dataset` and `name`) *is actually broken*. First of all `Relation::Name` is equalized only on `relation` and `dataset` attributes, so if there's an alias involved, it will not work. ~~It was too risky to fix it now because it's possible there's some code that relies on this equality behavior. It is something to address in 6.0.0.~~ I fixed it anyway in #563 
There's also another risk - equalizing on `Relation#dataset` *may result in materialization of the dataset*. I remember it happened in some cases in the past, that's why it was much better to use `Relation::Name#key` to figure out which nodes are duplicated. In theory, you can have more than one node with the same key but different datasets, but you would have to do …
=> [core] use Relation::Name's key for rejecting duped combine nodes

core/lib/rom/struct_compiler.rb, core/spec/unit/rom/struct_compiler_spec.rb
Fixing a bug that I found recently.
The actual culprit though is dry-rb/dry-inflector#27 - despite that, it still makes sense to just use `classify` as it does `singularize` under the hood.
=> [core] fix class name inference in struct compiler

core/lib/rom/commands/class_interface.rb
I got this warning when installing `rom-core-5.1.2`:
```
Installing darkfish documentation for rom-core-5.1.2
(eval):9: warning: key :arg1 is duplicated and overwritten on line 9
(eval):9: warning: key :arg1 is duplicated and overwritten on line 9
```
I believe it is related to this line.
=> Fix warning about shadowed arg1

repository/lib/rom/repository.rb, repository/spec/unit/repository/transaction_spec.rb
Currently, rom-repository does not pass arguments to the gateway. This makes it harder to use useful features such as [savepoints](https://www.postgresql.org/docs/8.1/sql-savepoint.html).
With this patch, all args are forwarded to the gateway for `ROM::Repository#transaction` calls.
=> Delegate args for transaction calls

changeset/lib/rom/changeset/pipe.rb, changeset/spec/integration/changeset_spec.rb
`map` blocks defined in `ROM::Changeset::Update` subclasses should be evaluated in the context of that changeset's _instance_, however, since the changes in https://github.com/rom-rb/rom/commit/d742f608958a5a6391f53165736f325a64d0066b, they're evaluated in the context of the changeset _class_.
This breaks ROM's documented behaviour and has caused some issues in an application I help with, which depends on the previous (non-broken) behaviour.
Of the 2 tests added here, only the test using an `Update` subclass fails, indicating that this behaviour is somehow specific to changesets using that superclass only.
=> [changeset] fix binding map functions in Changeset::Update

repository/lib/rom/repository.rb
If rom/repository is required directly, the `ROM::Plugins` namespace
might not exist yet.
Easily reproduced from the command line:
```
user@ef8029912cf4:/opt/rom/repository$ ruby -rbundler/setup -rrom/repository -e true
Traceback (most recent call last):
1: from -e:in `require'
/opt/rom/repository/lib/rom/repository.rb:12:in `<top (required)>': uninitialized constant ROM::Plugins (NameError)
```
Closes #598
=> Require plugins in repository

lib/rom/associations/definitions/abstract.rb, lib/rom/associations/through_identifier.rb, lib/rom/command_compiler.rb, lib/rom/command_proxy.rb, lib/rom/commands/class_interface.rb, lib/rom/configuration.rb, lib/rom/configuration_dsl/command.rb, lib/rom/configuration_dsl/relation.rb, lib/rom/create_container.rb, lib/rom/relation.rb, lib/rom/relation/class_interface.rb, lib/rom/schema/associations_dsl.rb, lib/rom/schema/dsl.rb, lib/rom/setup.rb, lib/rom/setup/auto_registration.rb, lib/rom/setup/auto_registration_strategies/base.rb, lib/rom/setup/auto_registration_strategies/custom_namespace.rb, lib/rom/setup/auto_registration_strategies/no_namespace.rb, lib/rom/setup/auto_registration_strategies/with_namespace.rb, lib/rom/setup/finalize.rb, lib/rom/setup/finalize/finalize_commands.rb, lib/rom/setup/finalize/finalize_relations.rb, lib/rom/struct_compiler.rb, spec/fixtures/xml_space/xml_commands/create_customer.rb, spec/fixtures/xml_space/xml_mappers/customer_list.rb, spec/fixtures/xml_space/xml_relations/customers.rb, spec/unit/rom/configuration_spec.rb, spec/unit/rom/relation/schema_spec.rb, spec/unit/rom/schema/associations_dsl_spec.rb, spec/unit/rom/setup/auto_registration_spec.rb
All components that rely on inflector use an injected inflector now rather than using a global `ROM::Inflector`. This makes it possible to configure a custom inflector like that:
```ruby
configuration = ROM::Configuration.new(:memory, "something") do |conf|
conf.inflector = my_custom_inflector
end
```
=> Allow to configure custom inflector

lib/rom/schema.rb, spec/unit/rom/schema/accessing_attributes_spec.rb
=> Make Schema#[] raise when attribute name is not unique

lib/rom/setup/auto_registration.rb
`Dir.glob` doesn't guarantee the order of listed files.
It is inconvenient and leads random fails on different platforms in different environments: development, CI, production etc.
It is recommended to sort required files listed by `Dir.glob`:
- [Rubocop](https://github.com/rubocop-hq/rubocop/blob/master/lib/rubocop/cop/lint/non_deterministic_require_order.rb)
- [Ruby 3](https://github.com/ruby/ruby/pull/2846/files)
=> Sort files before loading at auto-registration

lib/rom/support/configurable.rb
=> #616 Relax freezing policy for `ROM::Configurable`

docsite/changeset/source/mapping.html.md, docsite/core/source/mappers.html.md, lib/rom/changeset/pipe_registry.rb, lib/rom/processor/transformer.rb
`transproc` was replaced by `dry-transformer`, but there were still some references to it left in the docs.
=> Replace references to transproc by dry-transformer

core/docsite/source/framework-setup.html.md
Auto-registration already supports nesting namespaces, and those are accepted by ROM::AutoRegistration if specified properly with "::" in the namespace string.
This proposal is for documenting this use case.
=> Adds hint for auto-registration with nested namespaces

README.md
Hey, it seems like you restructured the repo - when I clicked on the links, I received 404s.
I _assume_ the links should point to these pages, but please ensure I guessed you intention correctly.
Once you confirm that, I could also fix the links on these _index.html.md_ pages.
=> Fix links to components in README

lib/rom/components/core.rb, lib/rom/configuration.rb, lib/rom/plugin_registry.rb, lib/rom/support/notifications.rb, spec/shared/changeset/database.rb, spec/shared/repository/database.rb
Trigger listeners only for enabled plugin
Previously any plugin that would subscribe to notifications would be
always triggered, which made it impossible to isolate plugin configs
=> Improve plugin setup

Gemfile, lib/rom/compat.rb, lib/rom/components.rb, lib/rom/components/core.rb, lib/rom/components/relation.rb, lib/rom/components/schema.rb, lib/rom/configuration_dsl.rb, lib/rom/configuration_dsl/relation.rb, lib/rom/constants.rb, lib/rom/container.rb, lib/rom/plugins/relation/registry_reader.rb, lib/rom/relation.rb, lib/rom/relation/class_interface.rb, lib/rom/relation/view_dsl.rb, lib/rom/runtime/configuration.rb, lib/rom/runtime/resolver.rb, spec/integration/relations/default_dataset_spec.rb, spec/unit/rom/relation/attribute_reader_spec.rb, spec/unit/rom/relation/class_interface/relation_name_spec.rb, spec/unit/rom/relation/class_interface/view_spec.rb, spec/unit/rom/relation/map_to_spec.rb, spec/unit/rom/relation/schema_spec.rb
Schemas are now part of the runtime, lazy-loaded and configured just
like all other components, and **they are decoupled from relations now**.
This drastically simplified handling
everything that may need access to schemas and further simplifications
are still possible.
This has a temporary breaking change because Relation.dataset receives
a schema now, instead of a relation class. I will restore original
behavior in rom/compat later on in a PR that will improve handling of
the default dataset (this is part of 6.0.0 feature scope).
Apart from lazy-loading, there's another big benefit of this refactor -
relation classes no longer hold their schemas as class variables. This
means that the same relation class can be re-used in the same process in
different configurations. It also means that …
=> 1st class schemas

lib/rom/components.rb, lib/rom/components/core.rb, lib/rom/components/dataset.rb, lib/rom/components/relation.rb, lib/rom/configuration.rb, lib/rom/configuration_dsl.rb, lib/rom/constants.rb, lib/rom/relation.rb, lib/rom/relation/class_interface.rb, lib/rom/runtime/resolver.rb, lib/rom/setup.rb, spec/compat/unit/setup/auto_registration_spec.rb, spec/integration/core/setup_spec.rb, spec/integration/gateways/extending_relations_spec.rb, spec/spec_helper.rb, spec/unit/rom/relation/class_interface/view_spec.rb
This adds lazy-loadable dataset components which makes the entire setup
consistent as now all core components are handled in the same way.
More features can be built on top of this new foundation, like
multi-gateway relations, caching specific datasets and more.
=> Introduce dataset components

lib/rom/runtime.rb, lib/rom/settings.rb, spec/suite/rom/runtime/register_relation_spec.rb
This makes inferring relation ids from constant names explicitly configurable, which will make things much simpler to handle. This behavior was previously implicit and caused *a lot of pain* in the code.
You can configure it "globally" within your runtime or on a per-relation class basis.
```ruby
> runtime = ROM::Runtime.new { |runtime| runtime.config.relation.infer_id_from_class = true }
=> #<ROM::Runtime:0x00007f6d4790bc10..>
irb(main):005:0> class Users < ROM::Relation; end
=> nil
irb(main):006:0> runtime.register_relation(Users)
=> [#<ROM::Components::Relation:0x00007f6d479b2740...]
> runtime.resolver["relations.users"]
=> #<Users name=ROM::Relation::Name(users) dataset=[]>
```
This can be done relatively easily for other component types too.
=> Add support for relation.infer_id_from_class setting

lib/rom/components/dataset.rb, lib/rom/components/dsl/dataset.rb, lib/rom/components/dsl/relation.rb, lib/rom/components/dsl/schema.rb, lib/rom/components/gateway.rb, lib/rom/components/registry.rb, lib/rom/components/schema.rb, lib/rom/relation.rb, lib/rom/resolver.rb, lib/rom/settings.rb, spec/suite/compat/unit/rom/relation/schema_spec.rb, spec/suite/rom/command_compiler_spec.rb, spec/suite/rom/components/provider_spec.rb, spec/suite/rom/relation/dataset_spec.rb, spec/suite/rom/relation/schema_spec.rb
This makes resolver store schemas and datasets under nested namespaces so that it's possible to connect a schema with a dataset using relation identifier. A dataset with an id that matches a schema id means that this schema should be passed to dataset block (when block is provided of course). It also ensures that abstract components are not being built through resolving, which was a bug previously.
=> Schema and dataset setup improvements

lib/rom/loader.rb, lib/rom/resolver.rb, lib/rom/runtime.rb, spec/fixtures/auto_loading/app/commands/users/create.rb, spec/fixtures/auto_loading/app/mappers/users/listing.rb, spec/fixtures/auto_loading/app/relations/users.rb, spec/fixtures/auto_loading/persistence/commands/tasks/create.rb, spec/fixtures/auto_loading/persistence/mappers/tasks/listing.rb, spec/fixtures/auto_loading/persistence/relations/tasks.rb, spec/suite/rom/runtime/auto_loading_spec.rb
This adds support for auto-loading of component files using Zeitwerk. All you need to do is this:
```ruby
rom = ROM.runtime(:sql, "sqlite::memory") do |cfg|
cfg.auto_register("path-to-component-dir", auto_load: true) # <= that's it
end
```
Once this is enabled, whenever you ask for a rom component, it will infer fully qualified constant name based on component's key and try to load a corresponding file using Zeitwerk auto-loading, ie:
- `rom.relations[:users]` => `Relations::Users` => `#{components_dir}/relations/users`
- `rom.mappers[:users][:listing]` => `Mappers::Users::Listing` => `#{components_dir}/mappers/users/listing`
If you have top-level namespace enabled, it will be prepended automatically, ie:
- `rom.relations[:users]` => `Persistence::Relations::Users` => …
=> Auto-loadable components

lib/rom/changeset.rb, lib/rom/command.rb, lib/rom/commands/class_interface.rb, lib/rom/compat/components/dsl/schema.rb, lib/rom/compat/schema/dsl.rb, lib/rom/components/core.rb, lib/rom/components/dsl.rb, lib/rom/components/dsl/core.rb, lib/rom/components/dsl/schema.rb, lib/rom/mapper.rb, lib/rom/mapper/dsl.rb, lib/rom/plugin.rb, lib/rom/plugins.rb, lib/rom/plugins/class_methods.rb, lib/rom/plugins/schema/timestamps.rb, lib/rom/relation.rb, lib/rom/relation/class_interface.rb, lib/rom/settings.rb, lib/rom/transformer.rb, spec/suite/rom/plugins/schema/timestamps_spec.rb, spec/suite/rom/plugins_spec.rb, spec/suite/rom/relation/class_interface/use_spec.rb, spec/suite/rom/runtime_spec.rb
This unifies `use` interface and improves internal handling of plugins so that all scenarios are still supported while at the same time it adds support for extending either DSL or component's constant (in a generic way). Plugins are now *configured in the settings* for each component, so that **you can actually see which plugins have been enabled for a given component instance**, ie:
```ruby
> users
#<ROM::Relations::Users name=ROM::Relation::Name(users) dataset=#...>
> users.config.component.plugins.detect { |pl| pl.name == :pg_explain }
#<ROM::Plugin type=:relation name=:pg_explain mod=ROM::Plugins::Relation::SQL::Postgres::Explain adapter=:sql config=#<ROM::OpenStruct {:enabled=>true, :target=>ROM::Relations::Users, :applied=>true}> dsl=nil>
```
With this done, it should be possible to …
=> Improve plugin API

README.md
Hi,  when I clicked on the links, I received 404s.
It looks like they have been fixed in the past, but they have reverted back to their original state, so I fixed them again.
cf. https://github.com/rom-rb/rom/pull/631
=> Fix components link in README

core/docsite/source/associations.html.md
`Types::Int` does not exist but `Types::Integer` does.
=> Fix the documentation of associations.html.md

core/lib/rom/struct.rb
Fixes #685
Also adds a **NOTE** in front of the caveat for ROM structs which was also discussed in #610
=> Fix ROM Struct examples
